### ISSUE TITLE
Vape crashs when sending config

### ISSUE THREAD

**Issue by CMCat-Xicheng** [DuckySoLucky/Vape-Lite#1]
title

**Comment by DuckySoLucky** [comment]
Hey, please contact me on discord DuckySoLucky#5181. So we can talk to each other faster. Also please send more details, like are u using forge or Lunar, which version etc..

**Comment by DuckySoLucky** [comment]
Solved, it was due to Python version

**Comment by CMCat-Xicheng** [comment]
Which Python version supporting saving config

**Comment by CMCat-Xicheng** [comment]
i mean vapelite ,not vape v4

**Comment by DuckySoLucky** [comment]
3.9 or 3.9.11

**Comment by CMCat-Xicheng** [comment]
u meant using 127.0.0.1 as the client and server ip wont work well?
idk how to edit server ip
i changed my python version to 3.9.11 but my vape lite still crashed

**Comment by DuckySoLucky** [comment]
Contact me on discord, so we can talk to each other faster. Also u are not suppose to edit any ip?
